### ISSUE TITLE
Define and implement usecases as commands

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/gy-bot#1]
The purpose of this issue is to implement every possible command and feature this BOT could provide related to the information recieved from Fall of the Gods API.

# Tasks
- [ ] Define every command and its way to implement it, based on how it would look on the Discord chat.
- [x] Implement it in the most efficient way possible.
- [ ] Set up logs to have information about every possible use of this bot.

In order for this issue to be closed, all tasks should be completed.
