### ISSUE TITLE
Link bot with Fall of the Gods API

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/gy-bot#3]
The purpose of this issue is to link the BOT to the Fall of the Gods API.

# Tasks
- [x] Prepare the fetching.
- [x] Test if it recieves information properly.
- [x] Set up all the interfaces and mappers for each collection of data.

In order for this issue to be closed, all tasks should be completed.
